---
version: "2.0"
services:
  app:
    image: morph42/voi-docker:2024-01-27
    expose:
      - port: 22
        as: 22
        accept:
          - {{ your ssh client IP }}
        proto: tcp
        to:
          - global: true
    params:
      storage:
        algorand:
          mount: /var/lib/algorand
          readOnly: false
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4
        memory:
          size: 8GB
        storage:
          - size: 1Gi
          - name: algorand
            size: 10Gi
            attributes:
              persistent: true
              class: beta2
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1